### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by tabyr** [Shini31/OVH-Server-Availability#4]
root@xxx:~/OVH-Server-Availability# perl -v
This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi

root@xxx:~/OVH-Server-Availability# ./ovh-server-availability.pl
syntax error at ./ovh-server-availability.pl line 88, near ") {"
syntax error at ./ovh-server-availability.pl line 91, near "}"
syntax error at ./ovh-server-availability.pl line 96, near "}"
syntax error at ./ovh-server-availability.pl line 101, near "}"
syntax error at ./ovh-server-availability.pl line 106, near "}"
syntax error at ./ovh-server-availability.pl line 111, near "}"
syntax error at ./ovh-server-availability.pl line 116, near "}"
syntax error at ./ovh-server-availability.pl line 129, near "}"
Execution of ./ovh-server-availability.pl aborted due to compilation errors.

Debian 8.9

Can you help me ?

**Comment by mcinquin** [comment]
I just fixed missing bracket.
You pull the repository and retry.

**Comment by tabyr** [comment]
thx work.
